// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6MtDj_RJpLHguvnJMtXDIvAmIkGhaxtc',
    appId: '1:541706128340:web:83bffbcaa469f43a7a6441',
    messagingSenderId: '541706128340',
    projectId: 'shram-daan-72a9b',
    authDomain: 'shram-daan-72a9b.firebaseapp.com',
    storageBucket: 'shram-daan-72a9b.firebasestorage.app',
    measurementId: 'G-YD3HXE9Z00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCznZbg185uiyH0Y6uNi4e81XhspxKIOO0',
    appId: '1:541706128340:android:32c6931405f21f717a6441',
    messagingSenderId: '541706128340',
    projectId: 'shram-daan-72a9b',
    storageBucket: 'shram-daan-72a9b.firebasestorage.app',
  );

}